# Generated by Django 4.0.5 on 2022-06-23 06:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('location', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('order_date', models.DateField(default=datetime.date(2022, 6, 23))),
                ('lunch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rms_app.foodmenu')),
            ],
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='restaurant_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rms_app.restaurantlist'),
        ),
    ]
