# Generated by Django 4.0.5 on 2022-06-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rms_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodmenu',
            old_name='restaurant_name',
            new_name='restaurant',
        ),
    ]
