# Generated by Django 4.0.5 on 2022-06-24 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rms_app', '0002_rename_restaurant_name_foodmenu_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='order_date',
            field=models.DateField(default=datetime.date(2022, 6, 24)),
        ),
    ]
